runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "gws-project-5345-d6f6c3dc800b.json"
  SECRET_KEY: "2a4a8665a383d0d2f72e5ddea7cd7c39ab9751bec931dd7b"
  SERVER_NAME: "23.23.229.9"
  SERVER_PORT: "5432"
  DB_USERNAME: "neondb_owner"
  PASSWORD: "5PVchsS3Roqr"
  DATABASE_NAME: "neondb"
  SSL_MODE: "require"
  ENDPOINT_ID: "ep-steep-grass-a4kycckd"
  SHEET_ID: "1QAJYqaQexw4tH8wFpCZlVkIgVb_2wWQ9x7haWLtzZyU"
  SHEET_NAME: "Setup"

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
